"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import mongoengine

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY or SECRET_KEY == 'django-insecure-k#at8^gnm@h96kpeozb==f0&a@5f8tjjegrzvg1388c^6o!wlm':
    raise ValueError(
        'SECRET_KEY no está configurado o usa el valor por defecto.\n'
        'Genera un secret seguro con: python -c "import secrets; print(secrets.token_urlsafe(50))"\n'
        'Luego agrégalo a tu archivo .env: SECRET_KEY=<valor_generado>'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Hosts permitidos (previene Host Header Injection)
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # TODO: Agregar dominios de producción aquí:
    # 'machtia.com',
    # 'api.machtia.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'apps.autenticacion',
    'apps.lecciones',
    'apps.progreso',
    'apps.vidas',
    'apps.tienda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe estar antes de CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================
# MONGODB CONFIGURATION
# ===========================
# SEGURIDAD: Requiere que MONGODB_URI esté configurado, sin fallback inseguro
MONGODB_URI = os.getenv('MONGODB_URI')
if not MONGODB_URI:
    raise ValueError(
        'MONGODB_URI no está configurado en el archivo .env.\n'
        'Genera credenciales seguras con: python generate_credentials.py\n'
        'Luego configura MONGODB_URI en el archivo .env'
    )

# Configurar conexión a MongoDB usando mongoengine
mongoengine.connect(
    db='nahuatl_db',
    host=MONGODB_URI,
    alias='default',
    connect=False  # Evita problemas de threading con Django
)

# ===========================
# CORS CONFIGURATION
# ===========================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend React (create-react-app)
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Frontend Vite
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

# Permitir todos los headers comunes para preflight
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permitir todos los métodos HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Cachear respuestas preflight por 24 horas
CORS_PREFLIGHT_MAX_AGE = 86400

# ===========================
# REST FRAMEWORK CONFIGURATION
# ===========================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # API navegable en desarrollo
    ],
}

# ===========================
# JWT CONFIGURATION
# ===========================
JWT_SECRET = os.getenv('JWT_SECRET')
if not JWT_SECRET or JWT_SECRET == 'tu_jwt_secret_aqui':
    raise ValueError(
        'JWT_SECRET no está configurado o usa el valor por defecto.\n'
        'Genera un secret seguro con: python -c "import secrets; print(secrets.token_urlsafe(50))"\n'
        'Luego agrégalo a tu archivo .env: JWT_SECRET=<valor_generado>'
    )
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_HOURS = 24

# ===========================
# SECURITY HEADERS (PRODUCCIÓN)
# ===========================
# Headers de seguridad HTTP - solo aplican cuando DEBUG=False (producción)
if not DEBUG:
    # Previene ataques XSS mediante el navegador
    SECURE_BROWSER_XSS_FILTER = True

    # Previene MIME type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Previene clickjacking
    X_FRAME_OPTIONS = 'DENY'

    # Fuerza uso de HTTPS
    SECURE_SSL_REDIRECT = True

    # Cookies solo por HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security (HSTS)
    # Fuerza HTTPS por 1 año (31536000 segundos)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
